import { Product } from './types';

export const CATEGORIES = [
  'Pain Relief',
  'Cold & Flu',
  'Vitamins & Supplements',
  'Skincare',
  'Digestive Health',
  'Prescription Only',
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Paracetamol 500mg',
    category: 'Pain Relief',
    price: 5000,
    description: 'Effective relief from mild to moderate pain including headache, migraine, toothache, and period pain. Also reduces fever.',
    imageUrl: 'https://picsum.photos/seed/paracetamol/400/400',
    requiresPrescription: false,
    stock: 150,
  },
  {
    id: 2,
    name: 'Vitamin C 1000mg',
    category: 'Vitamins & Supplements',
    price: 25000,
    description: 'High-strength Vitamin C tablets to support the immune system and reduce tiredness and fatigue.',
    imageUrl: 'https://picsum.photos/seed/vitaminc/400/400',
    requiresPrescription: false,
    stock: 200,
  },
  {
    id: 3,
    name: 'Amoxicillin 250mg',
    category: 'Prescription Only',
    price: 15000,
    description: 'A penicillin antibiotic that fights bacteria. Used to treat many different types of infection caused by bacteria.',
    imageUrl: 'https://picsum.photos/seed/amoxicillin/400/400',
    requiresPrescription: true,
    stock: 50,
  },
  {
    id: 4,
    name: 'Loratadine 10mg',
    category: 'Cold & Flu',
    price: 12000,
    description: 'An antihistamine that provides 24-hour relief from allergy symptoms such as sneezing, runny nose, and itchy eyes.',
    imageUrl: 'https://picsum.photos/seed/loratadine/400/400',
    requiresPrescription: false,
    stock: 80,
  },
  {
    id: 5,
    name: 'Cetaphil Gentle Skin Cleanser',
    category: 'Skincare',
    price: 45000,
    description: 'A mild, non-irritating formulation that soothes skin as it cleans. Gentle enough for a baby\'s delicate skin.',
    imageUrl: 'https://picsum.photos/seed/cetaphil/400/400',
    requiresPrescription: false,
    stock: 120,
  },
  {
    id: 6,
    name: 'Omeprazole 20mg',
    category: 'Digestive Health',
    price: 18000,
    description: 'Used to treat certain stomach and esophagus problems (such as acid reflux, ulcers). It works by decreasing the amount of acid your stomach makes.',
    imageUrl: 'https://picsum.photos/seed/omeprazole/400/400',
    requiresPrescription: true,
    stock: 90,
  },
  {
    id: 7,
    name: 'Ibuprofen 400mg',
    category: 'Pain Relief',
    price: 8000,
    description: 'A nonsteroidal anti-inflammatory drug (NSAID) used for relieving pain from various conditions such as headache, dental pain, and menstrual cramps.',
    imageUrl: 'https://picsum.photos/seed/ibuprofen/400/400',
    requiresPrescription: false,
    stock: 180,
  },
  {
    id: 8,
    name: 'Multivitamin Gummies',
    category: 'Vitamins & Supplements',
    price: 35000,
    description: 'A delicious way to get your daily dose of essential vitamins and minerals for overall health and wellness.',
    imageUrl: 'https://picsum.photos/seed/multivitamin/400/400',
    requiresPrescription: false,
    stock: 100,
  },
];
